name: Build

on:
  push:
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [release-gcc, release-clang]

    steps:
      - uses: actions/checkout@v4

      - name: Install libc++
        if: matrix.preset == 'release-clang'
        run: | 
          sudo apt-get update
          sudo apt-get install -y libc++-dev libc++abi-dev

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.preset }}
  macOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset release-clang

      - name: Build
        run: cmake --build --preset release-clang

      - name: Test
        run: ctest --preset release-clang
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: cmake --preset release-msvc

      - name: Build
        run: cmake --build --preset release-msvc

      - name: Test
        run: ctest --preset release-msvc
