name: Coverage

on:
  push:
  pull_request:

jobs:
  Coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install llvm and libc++
        run: sudo apt-get update && sudo apt-get install -y llvm libc++-dev libc++abi-dev
      
      - name: Configure
        run: cmake --preset coverage
      
      - name: Build
        run: cmake --build --preset coverage
      
      - name: Test
        run: |
          LLVM_PROFILE_FILE="coverage-%p.profraw" \
          ctest --preset coverage
      
      - name: Merge coverage data
        run: |
          find build/coverage -name '*.profraw' -print \
            | xargs llvm-profdata merge -sparse -o coverage.profdata

      - name: Generate coverage report
        run: |
          llvm-cov export \
            ./build/coverage/tests \
            -instr-profile=coverage.profdata \
            --ignore-filename-regex='(/usr/|/llvm/|_deps/|gtest|tests)' \
            -format=lcov > coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          fail_ci_if_error: true
          files: coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
